### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [HarshNandwani/Digital-Tijori#72]
First thanks for this nice tracker-free app! Did you already decide for a license, to make it "fully FOSS" (without a license declared, it's implicitly "all rights reserved")?

**Comment by HarshNandwani** [comment]
Hey @IzzySoft , at this point of time am not currently sure on which licence to make it available in.

Basically i want the code to remain open source so ither developers can learn but i do not need anyone else to use same app with their branding.

Will be updating that shortly.

**Comment by IzzySoft** [comment]
Then maybe some of the "more restrictive" licenses (requiring attribution and keeping the license, e.g. AGPL) might be worth looking at. [SPDX](https://spdx.org/licenses/) might be some help with choosing; concentrate on those licenses either approved by FSF or OSI (or ideally both) for being sure it's widely accepted in the FOSS world.

To give you some background on my question: I'm running [a FOSS repository](https://apt.izzysoft.de/fdroid) and was considering adopting your app into it – or in the long run even helping you getting it listed in an even more trusted place like [F-Droid](https://f-droid.org/). Both places require the apps to be FOSS, i.e. coming with an appropriate license. F-Droid has the stricter rules, so my repo often serves as "stepping stone" :wink:

OK, looking forward then to your decision. Thanks for taking care – and all the best with your project!

**Comment by HarshNandwani** [comment]
Hi @IzzySoft, currently am not interested in declaring a license, I just made this project to showcase my clean-architecture skills, and as a guide project for other android developers to learn. I would like to keep it that way.

**Comment by IzzySoft** [comment]
No prob, I of course accept that. Though it would have been nice :wink: All the best then!
